name: sync_stream_controller
version: 1.0.0
description: A custom stream controller that synchroneously send events, even on listening.
homepage: https://github.com/rrousselGit/sync_stream_controller
author: Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.3.4
